name: flutter_heatmap_calendar_longpress
description: Flutter heatmap calendar inspired by github contribution chart which includes traditional mode / calendar mode.
version: 0.4.0+1
homepage: https://github.com/devappmin/flutter_heatmap_calendar_longpress

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
